const materialsData = {
    tomestones: {
        causality: {
            id: 0,
            name: "Allagan Tomestones of Causality",
            icon: "/icons/allagan_tomestone_of_causality.png",
        },
        poetics: {
            id: 1,
            name: "Allagan Tomestones of Poetics",
            icon: "/icons/allagan_tomestone_of_poetics.png",
        },
        heliometry: {
            id: 2,
            name: "Allagan Tomestones of Heliometry",
            icon: "/icons/allagan_tomestone_of_heliometry.png",
        },
    },
    materials: {
        arr: {},
        heavensward: {},
        stormblood: {
            antiquated: [
                {
                    id: "msb0",
                    name: "Gil",
                    icon: "/icons/stormblood-icons/materials/gil.png",
                    reqTotal: 15000,
                    reqPerWeapon: 1000,
                    category: "antiquated",
                },
            ],
            anemos: [
                {
                    id: "msb1",
                    name: "Protean Crystal",
                    icon: "/icons/stormblood-icons/materials/protean_crystal.png",
                    reqTotal: 19500,
                    reqPerWeapon: 1300,
                    category: "anemos",
                },
                {
                    id: "msb2",
                    name: "Pazuzu's Feather",
                    icon: "/icons/stormblood-icons/materials/pazuzus_feather.png",
                    reqTotal: 45,
                    reqPerWeapon: 3,
                    category: "anemos",
                },
            ],
            elemental: [
                {
                    id: "msb3",
                    name: "Pagos Crystal",
                    icon: "/icons/stormblood-icons/materials/pagos_crystal.png",
                    reqTotal: 7500,
                    reqPerWeapon: 500,
                    category: "elemental",
                },
                {
                    id: "msb4",
                    name: "Frosted Protean Crystal",
                    icon: "/icons/stormblood-icons/materials/frosted_protean_crystal.png",
                    reqTotal: 465,
                    reqPerWeapon: 31,
                    category: "elemental",
                },
                {
                    id: "msb5",
                    name: "Louhi's Ice",
                    icon: "/icons/stormblood-icons/materials/louhis_ice.png",
                    reqTotal: 75,
                    reqPerWeapon: 5,
                    category: "elemental",
                },
            ],
            pyros: [
                {
                    id: "msb6",
                    name: "Pyros Crystal",
                    icon: "/icons/stormblood-icons/materials/pyros_crystal.png",
                    reqTotal: 9750,
                    reqPerWeapon: 650,
                    category: "pyros",
                },
                {
                    id: "msb7",
                    name: "Penthesilea's Flame",
                    icon: "/icons/stormblood-icons/materials/penthesileas_flame.png",
                    reqTotal: 75,
                    reqPerWeapon: 5,
                    category: "pyros",
                },
            ],
            eureka: [
                {
                    id: "msb8",
                    name: "Hydatos Crystal",
                    icon: "/icons/stormblood-icons/materials/hydatos_crystal.png",
                    reqTotal: 5250,
                    reqPerWeapon: 350,
                    category: "eureka",
                },
                {
                    id: "msb9",
                    name: "Crystalline Scale",
                    icon: "/icons/stormblood-icons/materials/crystalline_scale.png",
                    reqTotal: 75,
                    reqPerWeapon: 5,
                    category: "eureka",
                },
            ],
            physeos: [
                {
                    id: "msb10",
                    name: "Eureka Fragment",
                    icon: "/icons/stormblood-icons/materials/eureka_fragment.png",
                    reqTotal: 1500,
                    reqPerWeapon: 100,
                    category: "physeos",
                },
            ],
        },
        shadowbringers: {
            resistance: [
                {
                    id: "mshb0",
                    name: "Thavnairian Scalepowder",
                    icon: "/icons/shadowbringers-icons/materials/thavnairian_scalepowder.png",
                    reqTotal: 68,
                    reqPerWeapon: 4,
                    category: "resistance",
                },
            ],
            augmentedResistance: [
                {
                    id: "mshb1",
                    name: "Harrowing Memory of the Dying",
                    icon: "/icons/shadowbringers-icons/materials/harrowing_memory_of_the_dying.png",
                    reqTotal: 340,
                    reqPerWeapon: 20,
                    category: "augmentedResistance",
                },
                {
                    id: "mshb2",
                    name: "Sorrowful Memory of the Dying",
                    icon: "/icons/shadowbringers-icons/materials/sorrowful_memory_of_the_dying.png",
                    reqTotal: 340,
                    reqPerWeapon: 20,
                    category: "augmentedResistance",
                },
                {
                    id: "mshb3",
                    name: "Tortured Memory of the Dying",
                    icon: "/icons/shadowbringers-icons/materials/tortured_memory_of_the_dying.png",
                    reqTotal: 340,
                    reqPerWeapon: 20,
                    category: "augmentedResistance",
                },
            ],
            recollection: [
                {
                    id: "mshb4",
                    name: "Bitter Memory of the Dying",
                    icon: "/icons/shadowbringers-icons/materials/bitter_memory_of_the_dying.png",
                    reqTotal: 102,
                    reqPerWeapon: 6,
                    category: "recollection",
                },
            ],
            lawsOrder: [
                {
                    id: "mshb5",
                    name: "Loathsome Memory of the Dying",
                    icon: "/icons/shadowbringers-icons/materials/loathsome_memory_of_the_dying.png",
                    reqTotal: 255,
                    reqPerWeapon: 15,
                    category: "lawsOrder",
                },
            ],
            augmentedLawsOrder: [
                {
                    id: "mshb6",
                    name: "Timeworn Artifact",
                    icon: "/icons/shadowbringers-icons/materials/timeworn_artifact.png",
                    reqTotal: 255,
                    reqPerWeapon: 15,
                    category: "augmentedLawsOrder",
                },
            ],
            blades: [
                {
                    id: "mshb7",
                    name: "Raw Emotion",
                    icon: "/icons/shadowbringers-icons/materials/raw_emotion.png",
                    reqTotal: 255,
                    reqPerWeapon: 15,
                    category: "blades",
                },
            ],
        },
        endwalker: {
            dow: {
                manderville: [
                    {
                        id: "mew0",
                        name: "Manderium Meteorites",
                        icon: "/icons/endwalker-icons/materials/manderium_meteorite.png",
                        reqTotal: 57,
                        reqPerWeapon: 3,
                        category: "manderville",
                    },
                ],
                amazingManderville: [
                    {
                        id: "mew1",
                        name: "Complementary Chondrites",
                        icon: "/icons/endwalker-icons/materials/complementary_chondrite.png",
                        reqTotal: 57,
                        reqPerWeapon: 3,
                        category: "amazingManderville",
                    },
                ],
                majesticManderville: [
                    {
                        id: "mew2",
                        name: "Amplifying Achondrite",
                        icon: "/icons/endwalker-icons/materials/amplifying_achondrite.png",
                        reqTotal: 57,
                        reqPerWeapon: 3,
                        category: "majesticManderville",
                    },
                ],
                mandervillous: [
                    {
                        id: "mew3",
                        name: "Cosmic Crystallite",
                        icon: "/icons/endwalker-icons/materials/cosmic_crystallite.png",
                        reqTotal: 57,
                        reqPerWeapon: 3,
                        category: "mandervillous",
                    },
                ],
            },
            doL: {
                splendorous: {
                    whiteGatherersScrip: {
                        id: 23,
                        name: "White Gatherers' Scrip",
                        icon: "/icons/white_gatherers_scrip.png",
                        reqTotal: 3000,
                        reqPerWeapon: 1500,
                        category: "splendorous",
                    },
                },
                augmentedSplendorous: {
                    splendorousMinersComponent: {
                        id: 24,
                        name: "Splendorous Miner's Component",
                        icon: "/icons/endwalker-icons/materials/splendorous_crafters_component.png",
                        category: "augmentedSplendorous",
                    },
                    splendorousBotanistsComponent: {
                        id: 25,
                        name: "Splendorous Botanist's Component",
                        icon: "/icons/endwalker-icons/materials/splendorous_crafters_component.png",
                        category: "augmentedSplendorous",
                    },
                    splendorousFishingRodComponent: {
                        id: 26,
                        name: "Splendorous Fishing Rod Component",
                        icon: "/icons/endwalker-icons/materials/splendorous_crafters_component.png",
                        category: "augmentedSplendorous",
                    },
                    splendorousFishingReelComponent: {
                        id: 27,
                        name: "Splendorous Fishing Reel Component",
                        icon: "/icons/endwalker-icons/materials/splendorous_crafters_component.png",
                        category: "augmentedSplendorous",
                    },
                    connoisseursPrismstone: {
                        id: 28,
                        name: "Connoisseur's Prismstone",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_prismstone.png",
                        minCollectability: "570-999",
                        maxCollectability: "1000",
                        category: "augmentedSplendorous",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Prismstone",
                    },
                    connoisseursWattlePetribark: {
                        id: 29,
                        name: "Connoisseur's Wattle Petribark",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_wattle_petribark.png",
                        minCollectability: "570-999",
                        maxCollectability: "1000",
                        category: "augmentedSplendorous",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Wattle_Petribark",
                    },
                    splendorousWaterShard: {
                        id: 30,
                        name: "Splendorous Water Shard",
                        icon: "/icons/endwalker-icons/materials/splendorous_water_shard.png",
                        category: "augmentedSplendorous",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Splendorous_Water_Shard",
                    },
                    splendorousEarthShard: {
                        id: 31,
                        name: "Splendorous Earth Shard",
                        icon: "/icons/endwalker-icons/materials/splendorous_earth_shard.png",
                        category: "augmentedSplendorous",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Splendorous_Earth_Shard",
                    },
                    platinumSeahorse: {
                        id: 32,
                        name: "Platinum Seahorse",
                        icon: "/icons/endwalker-icons/materials/platinum_seahorse.png",
                        minCollectability: "47-109",
                        maxCollectability: "110+",
                        category: "augmentedSplendorous",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Platinum_Seahorse",
                    },
                    clavekeeper: {
                        id: 33,
                        name: "Clavekeeper",
                        icon: "/icons/endwalker-icons/materials/clavekeeper.png",
                        minCollectability: "283-664",
                        maxCollectability: "665+",
                        category: "augmentedSplendorous",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Clavekeeper",
                    },
                },
                crystalline: {
                    adaptiveMinersComponent: {
                        id: 34,
                        name: "Adaptive Miner's Component",
                        icon: "/icons/endwalker-icons/materials/adaptive_crafters_component.png",
                        category: "crystalline",
                    },
                    adaptiveBotanistsComponent: {
                        id: 35,
                        name: "Adaptive Botanist's Component",
                        icon: "/icons/endwalker-icons/materials/adaptive_crafters_component.png",
                        category: "crystalline",
                    },
                    adaptiveFishingRodComponent: {
                        id: 36,
                        name: "Adaptive Fishing Rod Component",
                        icon: "/icons/endwalker-icons/materials/adaptive_crafters_component.png",
                        category: "crystalline",
                    },
                    adaptiveFishingReelComponent: {
                        id: 37,
                        name: "Adaptive Fishing Reel Component",
                        icon: "/icons/endwalker-icons/materials/adaptive_crafters_component.png",
                        category: "crystalline",
                    },
                    connoisseursRedMalachite: {
                        id: 38,
                        name: "Connoisseur's Red Malachite",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_red_malachite.png",
                        minCollectability: "570-999",
                        maxCollectability: "1000",
                        category: "crystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Red_Malachite",
                    },
                    connoisseursLevinMint: {
                        id: 39,
                        name: "Connoisseur's Levin Mint",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_levin_mint.png",
                        minCollectability: "570-999",
                        maxCollectability: "1000",
                        category: "crystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Levin_Mint",
                    },
                    adaptiveFireCrystal: {
                        id: 40,
                        name: "Adaptive Fire Crystal",
                        icon: "/icons/endwalker-icons/materials/adaptive_fire_crystal.png",
                        category: "crystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Adaptive_Fire_Crystal",
                    },
                    adaptiveLightningCrystal: {
                        id: 41,
                        name: "Adaptive Lightning Crystal",
                        icon: "/icons/endwalker-icons/materials/adaptive_lightning_crystal.png",
                        category: "crystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Adaptive_Lightning_Crystal",
                    },
                    mirrorImage: {
                        id: 42,
                        name: "Mirror Image",
                        icon: "/icons/endwalker-icons/materials/mirror_image.png",
                        minCollectability: "9-20",
                        maxCollectability: "21+",
                        category: "crystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Mirror_Image",
                    },
                    spangledPirarucu: {
                        id: 43,
                        name: "Spangled Pirarucu",
                        icon: "/icons/endwalker-icons/materials/spangled_pirarucu.png",
                        minCollectability: "425-997",
                        maxCollectability: "998+",
                        category: "crystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Spangled_Pirarucu",
                    },
                },
                choraZoisCrystalline: {
                    customizedMinersComponent: {
                        id: 44,
                        name: "Customized Miner's Component",
                        icon: "/icons/endwalker-icons/materials/customized_miners_component.png",
                        category: "choraZoisCrystalline",
                    },
                    customizedBotanistsComponent: {
                        id: 45,
                        name: "Customized Botanist's Component",
                        icon: "/icons/endwalker-icons/materials/customized_botanists_component.png",
                        category: "choraZoisCrystalline",
                    },
                    customizedFishingRodComponent: {
                        id: 46,
                        name: "Customized Fishing Rod Component",
                        icon: "/icons/endwalker-icons/materials/customized_fishing_rod_component.png",
                        category: "choraZoisCrystalline",
                    },
                    customizedFishingReelComponent: {
                        id: 47,
                        name: "Customized Fishing Reel Component",
                        icon: "/icons/endwalker-icons/materials/customized_fishing_reel_component.png",
                        category: "choraZoisCrystalline",
                    },
                    connoisseursSoiledFemur: {
                        id: 48,
                        name: "Connoisseur's Soiled Femur",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_soiled_femur.png",
                        minCollectability: "570-999",
                        maxCollectability: "1000",
                        category: "choraZoisCrystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Soiled_Femur",
                    },
                    connoisseursMiracleApple: {
                        id: 49,
                        name: "Connoisseur's Miracle Apple",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_miracle_apple.png",
                        minCollectability: "570-999",
                        maxCollectability: "1000",
                        category: "choraZoisCrystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Miracle_Apple",
                    },
                    customIceCrystal: {
                        id: 50,
                        name: "Custom Ice Crystal",
                        icon: "/icons/endwalker-icons/materials/custom_ice_crystal.png",
                        category: "choraZoisCrystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Custom_Ice_Crystal",
                    },
                    customWindCrystal: {
                        id: 51,
                        name: "Custom Wind Crystal",
                        icon: "/icons/endwalker-icons/materials/custom_wind_crystal.png",
                        category: "choraZoisCrystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Custom_Wind_Crystal",
                    },
                    goldDustfish: {
                        id: 52,
                        name: "Gold Dustfish",
                        icon: "/icons/endwalker-icons/materials/gold_dustfish.png",
                        minCollectability: "82-192",
                        maxCollectability: "193+",
                        category: "choraZoisCrystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Gold_Dustfish",
                    },
                    forgivenMelancholy: {
                        id: 53,
                        name: "Forgiven Melancholy",
                        icon: "/icons/endwalker-icons/materials/forgiven_melancholy.png",
                        minCollectability: "322-757",
                        maxCollectability: "758+",
                        category: "choraZoisCrystalline",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Forgiven_Melancholy",
                    },
                },
                brilliant: {
                    brilliantMinersComponent: {
                        id: 54,
                        name: "Brilliant Miner's Component",
                        icon: "/icons/endwalker-icons/materials/brilliant_miners_component.png",
                        category: "brilliant",
                    },
                    brilliantBotanistsComponent: {
                        id: 55,
                        name: "Brilliant Botanist's Component",
                        icon: "/icons/endwalker-icons/materials/brilliant_botanists_component.png",
                        category: "brilliant",
                    },
                    brilliantFishingRodComponent: {
                        id: 56,
                        name: "Brilliant Fishing Rod Component",
                        icon: "/icons/endwalker-icons/materials/brilliant_fishing_rod_component.png",
                        category: "brilliant",
                    },
                    brilliantFishingReelComponent: {
                        id: 57,
                        name: "Brilliant Fishing Reel Component",
                        icon: "/icons/endwalker-icons/materials/brilliant_fishing_reel_component.png",
                        category: "brilliant",
                    },
                    connoisseurAurumRegisOre: {
                        id: 58,
                        name: "Connoisseur's Aurum Regis Ore",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_aurum_regis_ore.png",
                        minCollectability: "570-999",
                        maxCollectability: "1000",
                        category: "brilliant",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Aurum_Regis_Ore",
                    },
                    connoisseursCloves: {
                        id: 59,
                        name: "Connoisseur's Cloves",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_cloves.png",
                        minCollectability: "570-999",
                        maxCollectability: "1000",
                        category: "brilliant",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Cloves",
                    },
                    brilliantLightningCluster: {
                        id: 60,
                        name: "Brilliant Lightning Cluster",
                        icon: "/icons/endwalker-icons/materials/brilliant_lightning_cluster.png",
                        category: "brilliant",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Brilliant_Lightning_Cluster",
                    },
                    brilliantEarthCluster: {
                        id: 61,
                        name: "Brilliant Earth Cluster",
                        icon: "/icons/endwalker-icons/materials/brilliant_earth_cluster.png",
                        category: "brilliant",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Brilliant_Earth_Cluster",
                    },
                    oilSlick: {
                        id: 62,
                        name: "Oil Slick",
                        icon: "/icons/endwalker-icons/materials/oil_slick.png",
                        minCollectability: "94-219",
                        maxCollectability: "220+",
                        category: "brilliant",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Oil_Slick",
                    },
                    gonzalosGrace: {
                        id: 63,
                        name: "Gonzalo's Grace",
                        icon: "/icons/endwalker-icons/materials/gonzalos_grace.png",
                        minCollectability: "47-109",
                        maxCollectability: "110+",
                        category: "brilliant",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Gonzalo%27s_Grace",
                    },
                },
                vrandticVisionarys: {
                    connoisseursAsphaltum: {
                        id: 64,
                        name: "Connoisseur's Asphaltum",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_asphaltum.png",
                        minCollectability: "570-999",
                        maxCollectability: "1000",
                        category: "vrandticVisionarys",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Asphaltum",
                    },
                    inspirationalMinersComponent: {
                        id: 65,
                        name: "Inspirational Miner's Component",
                        icon: "/icons/endwalker-icons/materials/inspirational_miners_component.png",
                        category: "vrandticVisionarys",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Inspirational_Miner%27s_Component",
                    },
                    inspirationalWindCluster: {
                        id: 66,
                        name: "Inspirational Wind Cluster",
                        icon: "/icons/endwalker-icons/materials/inspirational_wind_cluster.png",
                        category: "vrandticVisionarys",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Inspirational_Wind_Cluster",
                    },
                    connoisseurGianthiveChip: {
                        id: 67,
                        name: "Connoisseur's Gianthive Chip",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_gianthive_chip.png",
                        minCollectability: "570-999",
                        maxCollectability: "1000",
                        category: "vrandticVisionarys",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Gianthive_Chip",
                    },
                    inspirationalBotanistsComponent: {
                        id: 68,
                        name: "Inspirational Botanist's Component",
                        icon: "/icons/endwalker-icons/materials/inspirational_botanists_component.png",
                        category: "vrandticVisionarys",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Inspirational_Botanist%27s_Component",
                    },
                    inspirationalFireCluster: {
                        id: 69,
                        name: "Inspirational Fire Cluster",
                        icon: "/icons/endwalker-icons/materials/inspirational_fire_cluster.png",
                        category: "vrandticVisionarys",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Inspirational_Fire_Cluster",
                    },
                    deadwoodShadow: {
                        id: 70,
                        name: "Deadwood Shadow",
                        icon: "/icons/endwalker-icons/materials/deadwood_shadow.png",
                        minCollectability: "501-1176",
                        maxCollectability: "1177+",
                        category: "vrandticVisionarys",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Deadwood_Shadow",
                    },
                    ronkanBullion: {
                        id: 71,
                        name: "Ronkan Bullion",
                        icon: "/icons/endwalker-icons/materials/ronkan_bullion.png",
                        minCollectability: "501-1176",
                        maxCollectability: "1177+",
                        category: "vrandticVisionarys",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Ronkan_Bullion",
                    },
                    inspirationalFishersComponent: {
                        id: 72,
                        name: "Inspirational Fisher's Component",
                        icon: "/icons/endwalker-icons/materials/inspirational_fishers_component.png",
                        category: "vrandticVisionarys",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Inspirational_Fisher%27s_Component",
                    },
                },
                lodestar: {
                    connoisseursRawOnyx: {
                        id: 73,
                        name: "Connoisseur's Raw Onyx",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_raw_onyx.png",
                        minCollectability: "580-999",
                        maxCollectability: "1000",
                        category: "lodestar",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Raw_Onyx",
                    },
                    nightforgedMinersComponent: {
                        id: 74,
                        name: "Nightforged Miner's Component",
                        icon: "/icons/endwalker-icons/materials/nightforged_miners_component.png",
                        category: "lodestar",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Nightforged_Miner%27s_Component",
                    },
                    nightforgedIceCluster: {
                        id: 75,
                        name: "Nightforged Ice Cluster",
                        icon: "/icons/endwalker-icons/materials/nightforged_ice_cluster.png",
                        category: "lodestar",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Nightforged_Ice_Cluster",
                    },
                    connoisseursGlimshroom: {
                        id: 76,
                        name: "Connoisseur's Glimshroom",
                        icon: "/icons/endwalker-icons/materials/connoisseurs_glimshroom.png",
                        minCollectability: "570-999",
                        maxCollectability: "1000",
                        category: "lodestar",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Connoisseur%27s_Glimshroom",
                    },
                    nightforgedBotanistsComponent: {
                        id: 77,
                        name: "Nightforged Botanist's Component",
                        icon: "/icons/endwalker-icons/materials/nightforged_botanists_component.png",
                        category: "lodestar",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Nightforged_Botanist%27s_Component",
                    },
                    nightforgedWaterCluster: {
                        id: 78,
                        name: "Nightforged Water Cluster",
                        icon: "/icons/endwalker-icons/materials/nightforged_water_cluster.png",
                        category: "lodestar",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Nightforged_Water_Cluster",
                    },
                    littleBounty: {
                        id: 79,
                        name: "Little Bounty",
                        icon: "/icons/endwalker-icons/materials/little_bounty.png",
                        minCollectability: "9-20",
                        maxCollectability: "21+",
                        category: "lodestar",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Little_Bounty",
                    },
                    saintFathricsFace: {
                        id: 80,
                        name: "Saint Fathric's Face",
                        icon: "/icons/endwalker-icons/materials/saint_fathrics_face.png",
                        minCollectability: "384-901",
                        maxCollectability: "902+",
                        category: "lodestar",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Saint_Fathric%27s_Face",
                    },
                    nightforgedFishersComponent: {
                        id: 81,
                        name: "Nightforged Fisher's Component",
                        icon: "/icons/endwalker-icons/materials/nightforged_fishers_component.png",
                        category: "lodestar",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Nightforged_Fisher%27s_Component",
                    },
                },
            },
            doH: {
                splendorous: {
                    whiteCraftersScrip: {
                        id: 22,
                        name: "White Crafters' Scrip",
                        icon: "/icons/white_crafters_scrip.png",
                        reqTotal: 10500,
                        reqPerWeapon: 1500,
                        category: "splendorous",
                    },
                },
            },
        },
        dawntrail: {
            dow: {
                penumbrae: [
                    {
                        id: "mdt0",
                        name: "Arcanite",
                        icon: "/icons/dawntrail-icons/materials/arcanite.png",
                        category: "penumbrae",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Arcanite",
                        reqTotal: 63,
                        reqPerWeapon: 3,
                    },
                    {
                        id: "mdt1",
                        name: "Azurite Demiatma",
                        icon: "/icons/dawntrail-icons/materials/azurite_demiatma.png",
                        category: "penumbrae",
                        reqTotal: 3,
                        reqPerWeapon: 3,
                    },
                    {
                        id: "mdt2",
                        name: "Caput Mortuum Demiatma",
                        icon: "icons/dawntrail-icons/materials/caput_mortuum_demiatma.png",
                        category: "penumbrae",
                        reqTotal: 3,
                        reqPerWeapon: 3,
                    },
                    {
                        id: "mdt3",
                        name: "Malachite Demiatma",
                        icon: "icons/dawntrail-icons/materials/malachite_demiatma.png",
                        category: "penumbrae",
                        reqTotal: 3,
                        reqPerWeapon: 3,
                    },
                    {
                        id: "mdt4",
                        name: "Orpiment Demiatma",
                        icon: "icons/dawntrail-icons/materials/orpiment_demiatma.png",
                        category: "penumbrae",
                        reqTotal: 3,
                        reqPerWeapon: 3,
                    },
                    {
                        id: "mdt5",
                        name: "Realgar Demiatma",
                        icon: "icons/dawntrail-icons/materials/realgar_demiatma.png",
                        category: "penumbrae",
                        reqTotal: 3,
                        reqPerWeapon: 3,
                    },
                    {
                        id: "mdt6",
                        name: "Verdigris Demiatma",
                        icon: "icons/dawntrail-icons/materials/verdigris_demiatma.png",
                        category: "penumbrae",
                        reqTotal: 3,
                        reqPerWeapon: 3,
                    },
                ],
                umbrae: [
                    {
                        id: "mdt7",
                        name: "Waxing Arcanite",
                        icon: "/icons/dawntrail-icons/materials/waxing_arcanite.png",
                        category: "umbrae",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Waxing_Arcanite",
                        reqTotal: 63,
                        reqPerWeapon: 3,
                    },
                    {
                        id: "mdt8",
                        name: "Rroneek Glue",
                        icon: "/icons/dawntrail-icons/materials/rroneek_glue.png",
                        category: "umbrae",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Rroneek_Glue",
                        reqTotal: 1,
                        reqPerWeapon: 1,
                    },
                    {
                        id: "mdt9",
                        name: "Ut'ohmu Siderite",
                        icon: "/icons/dawntrail-icons/materials/utohmu_siderite.png",
                        category: "umbrae",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Ut%27ohmu_Siderite",
                        reqTotal: 1,
                        reqPerWeapon: 1,
                    },
                    {
                        id: "mdt10",
                        name: "Synthetic Dark Matter Alpha",
                        icon: "/icons/dawntrail-icons/materials/synthetic_dark_matter_alpha.png",
                        category: "umbrae",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Synthetic_Dark_Matter_Alpha",
                        reqTotal: 1,
                        reqPerWeapon: 1,
                    },
                    {
                        id: "mdt11",
                        name: "Synthetic Dark Matter Beta",
                        icon: "/icons/dawntrail-icons/materials/synthetic_dark_matter_beta.png",
                        category: "umbrae",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Synthetic_Dark_Matter_Beta",
                        reqTotal: 1,
                        reqPerWeapon: 1,
                    },
                    {
                        id: "mdt12",
                        name: "Synthetic Dark Matter Gamma",
                        icon: "/icons/dawntrail-icons/materials/synthetic_dark_matter_gamma.png",
                        category: "umbrae",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Synthetic_Dark_Matter_Gamma",
                        reqTotal: 1,
                        reqPerWeapon: 1,
                    },
                    {
                        id: "mdt13",
                        name: "Aetherwell Array",
                        icon: "/icons/dawntrail-icons/materials/aetherwell_array.png",
                        category: "umbrae",
                        wiki: "https://ffxiv.consolegameswiki.com/wiki/Aetherwell_Array",
                        reqTotal: 1,
                        reqPerWeapon: 1,
                    }
                ],
            },
            doL: {},
            doH: {},
        },
    },
};

export default materialsData;
